moonlight:
    _target_: verl.workers.config.RewardModelConfig
    reward_manager: naive
    enable: true
    enable_resource_pool: true
    n_gpus_per_node: 4
    nnodes: 2

    rollout:
        _target_: verl.workers.config.RolloutConfig
        name: sglang 
        response_length: 2048
        dtype: bfloat16
        gpu_memory_utilization: 0.8
        log_prob_micro_batch_size_per_gpu: 16
        enforce_eager: false
        free_cache_engine: true
        tensor_model_parallel_size: 1
        data_parallel_size: 1
        max_num_seqs: 256
        load_format: safetensors
        
        server:
            timeout: 6000.0
            max_attempts: 10
            retry_delay: 10.0
            max_connections: 1024
            max_start_wait_time: 6000.0

    model:
        _target_: verl.workers.config.HFModelConfig
        trust_remote_code: true
        use_fused_kernels: true
        path: "moonshotai/Moonlight-16B-A3B-Instruct"
        external_lib: ${actor_rollout_ref.model.external_lib}
