hydra:
  searchpath:
    - file://verl/trainer/config

defaults:
    - ppo_trainer
    - reward_models@multi_reward_model.reward_models:
      - llama
      - apertus
      - qwen
    - _self_

multi_reward_model:
    enable: true

data:
    train_batch_size: 1024
    max_prompt_length: 1024
    max_response_length: 1024
    return_raw_chat: true
